name: Links

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: corepack enable && corepack install
      - name: testtesttesttest
        run: ls
      - name: Install dependencies
        run: "yarn install"
      - name: Build documentation website
        run: "yarn run build"
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --fallback-extensions mdx --exclude-path "./node_modules" --exclude "http(s?)://localhost" "./**/*.mdx" "./**/*.md"
          lycheeVersion: nightly